language: python

python:
  - "3.5"

sudo: true

before_script:
  - pip install -r test-requirements.txt
  - python setup.py install

script:
  - python setup.py install
  - coala-ci
  - pytest --cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
